# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

# git clone 後、実行すべきコマンドがある場合はこんな感じ
[[plugins]]
repo = 'Shougo/vimproc.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'scrooloose/nerdcommenter'

[[plugins]]
repo = 'Shougo/vimshell'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'mileszs/ack.vim'

[[plugins]]
repo = 'Shougo/vimfiler'

#[[plugins]]
#repo = 'Lokaltog/vim-powerline'

[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'othree/eregex.vim'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'kana/vim-smartchr'

[[plugins]]
repo = 'rhysd/accelerated-jk'

[[plugins]]
repo = 'vim-scripts/Align'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-scripts/snipmate-snippets'

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'tpope/vim-markdown'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'mattn/httpstatus-vim'

#[[plugins]]
#repo = 'itchyny/calendar.vim'

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo   = 'Shougo/unite.vim'

[[plugins]]
repo      = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo = 'h1mesuke/unite-outline'
on_source = ['unite.vim']

[plugins.build]
windows = 'tools\\update-dll-mingw'
cygwin  = 'make -f make_cygwin.mak'
mac     = 'make -f make_mac.mak'
linux   = 'make'
unix    = 'gmake'

# 特定の条件で読み込みたいとき
[[plugins]]
repo = 'elzr-vim-json'
if   = '''! has('kaoriya')'''

# 依存関係を指定したいとき
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

# 依存関係を指定したからと言って、自動でインストールはされない（ここは NeoBundle と違う）
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
